### Create a report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "corolla",
    "year": 1980,
    "milesTravelled": 10000,
    "lng": 0,
    "lat": 0,
    "price": 400000
}


### Approve or Disapprove an existing report
PATCH http://localhost:3000/reports/1
content-type: application/json

{
    "approved": true
}


### Get an estimation for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=corolla&lng=0&lat=0&milesTravelled=10000&year=1980