### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "unique@gmail.com",
    "password": "helloworld123"
}


### Login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "unique@gmail.com",
    "password": "helloworld123"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami


### Logout
POST http://localhost:3000/auth/logout

### Find a user by ID
GET http://localhost:3000/auth/2 


### Find all users with a given email
GET http://localhost:3000/auth?email=unique@gmail.com


### Update a user with given ID
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email": "new-email@gmail.com"
}


### Delete a user with given ID
DELETE http://localhost:3000/auth/2


### Set color
GET http://localhost:3000/auth/set-color/red

### Get color 
GET http://localhost:3000/auth/color